<a href="https://colab.research.google.com/github/aviraltyagi/MLBasics/blob/main/Basic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Numpy Array

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [26]:
b = np.array([(1,2,3),
              (4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
c = np.array([[(1,2,3),
               (4,5,6)],
              [(7,8,9),
               (10,11,12)]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
d = np.zeros((2,2), dtype= int)
d

array([[0, 0],
       [0, 0]])

In [6]:
e = np.ones((2,3), dtype= float)
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
f = np.arange(1,5, dtype= float)
f

array([1., 2., 3., 4.])

## Inspecting Array

In [9]:
c.shape

(2, 2, 3)

In [10]:
len(c)

2

In [11]:
c.ndim

3

In [12]:
c.size

12

In [13]:
c.dtype

dtype('int64')

In [14]:
c.dtype.name

'int64'

In [17]:
c = c.astype(float)
c.dtype.name

'float64'

## Array Manipulation

In [18]:
print(b)
b_T = np.transpose(b)
print(b_T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [19]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [20]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
b.resize(1,6)
b

array([[1, 2, 3, 4, 5, 6]])

In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.append(a,b)

array([1, 2, 3, 4, 5, 6])

In [42]:
np.insert(a, 3, 1)

array([1, 2, 3, 1])

In [43]:
np.delete(a, 2)

array([1, 2])

## Combining Arrays

In [44]:
a = np.array([(1,2,3),
              (4,5,6)])

b = np.array([(7,8,9),
              (10,11,12)])

c = np.concatenate((a,b), axis=1)
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [46]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])